namespace Yello.Domain.Spaces;

/// <summary>
/// A Space: the boundary every Project, Task and Membership lives inside.
/// </summary>
/// <remarks>
/// <para>
/// <b>There is exactly one kind of Space, and this class is the proof.</b> The Space provisioned
/// at registration is called a "Personal Space" descriptively and nothing more -
/// <c>glossary.md:10</c> says "Descriptive only, not a distinct type", and
/// <c>decisions-settled.md:26</c> records "a distinct undeletable type" and "a permanently
/// private type" as explicitly <i>rejected</i>. So there is no <c>IsPersonal</c> flag, no
/// boolean, no subtype, no discriminator column, no separate table and no special lifecycle
/// rule. AC4 requires this be proved by comparison rather than asserted, and the absence of any
/// distinguishing member here is half of that proof; the other half is in the slice tests.
/// </para>
/// <para>
/// <b>Ownership is a <see cref="Memberships.Membership"/> at Role <c>Owner</c>, never an
/// <c>OwnerId</c> column here.</b> <c>addendum.md:33</c> settles that, and
/// <c>harness-constraints.md:101</c> records the consequence that makes it matter: erasure under
/// FR-3 holds only because ownership cannot be forced onto an Account. An <c>OwnerId</c> on this
/// table would be a foreign key an Account could not walk away from, and deleting the Account
/// would either fail or orphan the Space. AD-5's filtered unique index is what keeps the
/// invariant - exactly one Owner Membership per Space - without that column existing.
/// </para>
/// </remarks>
public sealed class Space
{
    /// <summary>
    /// The Space's identity, and the value the row-level security session context is set to for
    /// every unit of work that touches Space-scoped data.
    /// </summary>
    /// <remarks>
    /// Generated application-side (<see cref="IIdentifierGenerator"/>), which is what resolves
    /// the seam AD-2 leaves at registration: the session context has to be set from
    /// <c>ActiveSpaceContext</c> and never from a client-supplied value, yet registration is
    /// unauthenticated and creates the very Space whose id the context needs. Because the id is
    /// generated by the server before the insert, the slice can set the context to it inside the
    /// transaction and honour the prohibition rather than bypass it.
    /// </remarks>
    public required Guid Id { get; init; }

    /// <summary>
    /// The Space's name. Renameable on the same terms as any other Space, from Epic 3.
    /// </summary>
    /// <remarks>
    /// At registration this is composed by <see cref="PersonalSpaceName"/> - the single choke
    /// point the naming decision lives behind - and it is an ordinary column thereafter. Nothing
    /// records that the name was derived, because nothing may distinguish this Space from one
    /// created by any other route.
    /// </remarks>
    public required string Name { get; set; }

    /// <summary>
    /// When the Space was created, in UTC.
    /// </summary>
    public required DateTimeOffset CreatedAt { get; init; }
}
